name: Main Branch Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      contents: read
