name: Pull Request Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
