name: Publish Package

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      contents: read

  publish:
    name: Publish @castlabs/prettier-tsdoc-plugin
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TSDOC_WRITE }}
        run: npm publish --access public

  publish-gpr:
    name: Publish to GitHub Package Registry
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Package Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --access public
